export enum InternalErrorCodes {
  NOT_ENOUGH_LOCKED = 'NOT_ENOUGH_LOCKED',
  NOT_ENOUGH_AVAILABLE = 'NOT_ENOUGH_AVAILABLE',
  NO_CREDENTIALS = 'NO_CREDENTIALS',
  FILTER_DOES_NOT_EXIST = 'FILTER_DOES_NOT_EXIST'
}